name: 'ESLint (JS/TS) Action '
description: 'Lints JavaScript/TypeScript code.'
author: 'iCrawl'
branding:
  icon: check-circle
  color: yellow
inputs:
  custom-glob:
    description: 'Custom glob to overwrite which files to lint.'
    required: false
    default: 'src'
  max-warnings:
    description: 'Max warnings'
    required: false
    default: '-1'
runs:
  using: 'node16'
  main: 'dist/index.js'
